# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genotyping_error_model <- function(phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_genotyping_error_model`, phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate)
}

genotyping_error_model_class <- function(phenotype, genotype0, genotype1) {
    .Call(`_sydneyPaternity_genotyping_error_model_class`, phenotype, genotype0, genotype1)
}

simulate_genotyping_errors <- function(phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_simulate_genotyping_errors`, phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate)
}

sample_error_rates_given_paternity <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate, max_iter = 1000L) {
    .Call(`_sydneyPaternity_sample_error_rates_given_paternity`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate, max_iter)
}

paternity_loglikelihood_by_locus <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_paternity_loglikelihood_by_locus`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate)
}

paternity_loglikelihood <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_paternity_loglikelihood`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate)
}

recode_to_contiguous_integers <- function(input) {
    .Call(`_sydneyPaternity_recode_to_contiguous_integers`, input)
}

optimize_paternity_given_error_rates <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_optimize_paternity_given_error_rates`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate)
}

sample_paternity_given_error_rates <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate, max_iter) {
    .Call(`_sydneyPaternity_sample_paternity_given_error_rates`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate, max_iter)
}

