# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genotyping_error_model <- function(phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_genotyping_error_model`, phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate)
}

genotyping_error_model_class <- function(phenotype, genotype0, genotype1) {
    .Call(`_sydneyPaternity_genotyping_error_model_class`, phenotype, genotype0, genotype1)
}

simulate_genotyping_errors <- function(phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_simulate_genotyping_errors`, phenotype, genotype0, genotype1, number_of_alleles, dropout_rate, mistyping_rate)
}

sample_error_rates_given_paternity <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate, max_iter = 1000L, global_genotyping_error_rates = FALSE) {
    .Call(`_sydneyPaternity_sample_error_rates_given_paternity`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate, max_iter, global_genotyping_error_rates)
}

paternity_loglikelihood_by_locus <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_paternity_loglikelihood_by_locus`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate)
}

paternity_loglikelihood <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_paternity_loglikelihood`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate)
}

optimize_paternity_given_error_rates <- function(paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate) {
    .Call(`_sydneyPaternity_optimize_paternity_given_error_rates`, paternity, offspring_phenotypes, maternal_phenotype, allele_frequencies, dropout_rate, mistyping_rate)
}

collapse_alleles_and_generate_prior_wrapper <- function(offspring_phenotypes, maternal_phenotype, add_unsampled_allele = TRUE) {
    .Call(`_sydneyPaternity_collapse_alleles_and_generate_prior_wrapper`, offspring_phenotypes, maternal_phenotype, add_unsampled_allele)
}

sample_paternity_and_error_rates_from_joint_posterior <- function(offspring_phenotypes, maternal_phenotype, number_of_mcmc_samples = 1000L, use_global_genotyping_error_rates = TRUE) {
    .Call(`_sydneyPaternity_sample_paternity_and_error_rates_from_joint_posterior`, offspring_phenotypes, maternal_phenotype, number_of_mcmc_samples, use_global_genotyping_error_rates)
}

